const fs = require('fs');

/**
 * Adapts CSS theme variables for use in popup samples.
 */
const makeSampleCss = () => {
  const themes = fs.readFileSync('./extension/themes.css', 'utf8');
  const reClassName = /^\.coology-(\w+) \{/;
  const popupCss = themes
    .split('\n')
    .map((line) => line.replace(reClassName, (match, p1) => `[value="${p1}"] + samp {`))
    .join('\n');
  fs.writeFileSync('./extension/themesPopup.css', `/* GENERATED by makeSampleCss.js */\n${popupCss}`);
};

makeSampleCss();

/**
 * Watch for file changes (helpful during development).
 */
if (process.argv[2] && process.argv[2] === '--watch') {
  fs.watch('./extension/themes.css', (evType, filename) => {
    console.log(`Variables changed in "${filename}" applied to "themesPopup.css".`);

    makeSampleCss();
  });
}
